FROM python:3.12-slim

# Keep terminal output immediate and avoid generated bytecode in the workspace.
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1

# Git is used locally by git_diff; runtime networking remains disabled.
RUN apt-get update && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home --uid 10001 agent
WORKDIR /workspace

# Copy a snapshot, rather than mounting the live repository into the container.
COPY --chown=agent:agent pyproject.toml README.md ./
COPY --chown=agent:agent src/ ./src/
# Install the test runner before the container is run without networking.
RUN python -m pip install --no-cache-dir . "pytest==9.1.1" \
    && chown agent:agent /workspace

USER agent
CMD ["agentlens"]
